// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://rtg7mrrp6raatj7djfcbc4cbcm.appsync-api.us-east-1.amazonaws.com/graphql',
          region: 'us-east-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-wrypmiw4jvbczlwxj6i7tcg4te'
        }
    }
};

export default config;